
Encoding:
  Enabled: false

LineLength:
  Max: 300

HashSyntax:
  EnforcedStyle: hash_rockets

IfUnlessModifier:
  Enabled: false

MethodLength:
  Max: 11

TrivialAccessors:
  ExactNameMatch: true

inherit_from: rubocop-todo.yml
